version: '2.1'

services:
  datasource:
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=1q2w3e4r
    hostname: datasource
    ports:
    - 5444:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    image: online-todo-list-backend:v1.0
    hostname: backend
    ports:
    - 8090:8090
    depends_on:
      datasource:
        condition: service_healthy
    environment:
    - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    - spring.datasource.url=jdbc:postgresql://datasource:5432/postgres
    - spring.datasource.username=postgres
    - spring.datasource.password=1q2w3e4r

  frontend:
    build: ./online-todo-list-web
    image: online-todo-list-frontend:v1.0
    hostname: frontend
    depends_on:
    - backend
    environment:
    - NODE_ENV=production
    - BACKEND_HOSTNAME=localhost
    ports:
    - 8080:8080
    command: npm start
